-- CreateTable
CREATE TABLE "site_settings" (
    "id" UUID NOT NULL,
    "site_name" TEXT NOT NULL,
    "site_description" TEXT NOT NULL,
    "contact_email" TEXT NOT NULL,
    "facebook_url" TEXT,
    "twitter_url" TEXT,
    "instagram_url" TEXT,
    "meta_title" TEXT,
    "meta_description" TEXT,
    "meta_keywords" TEXT,
    "meta_keyphrases" TEXT,
    "site_tag" TEXT,
    "og_image_url" TEXT,
    "light_logo_url" TEXT,
    "dark_logo_url" TEXT,
    "icon_url" TEXT,
    "favicon_url" TEXT,
    "footer_description" TEXT,
    "footer_email" TEXT,
    "footer_phone" TEXT,
    "footer_address" TEXT,
    "contact_phone" TEXT,
    "contact_email_address" TEXT,
    "contact_address" TEXT,
    "contact_map_url" TEXT,
    "smtp_host" TEXT,
    "smtp_port" INTEGER,
    "smtp_user" TEXT,
    "smtp_pass" TEXT,
    "smtp_from_email" TEXT,
    "smtp_from_name" TEXT,
    "stripe_public_key" TEXT,
    "stripe_secret_key" TEXT,
    "stripe_webhook_secret" TEXT,
    "fcm_server_key" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "site_settings_pkey" PRIMARY KEY ("id")
);
